  version: "1.0.13T"
  services:
    config:
      image: config:latest
      container_name: config
      expose:
        - "8888"
      ports:
        - "8888:8888"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
    discovery:
      image: discovery:latest
      container_name: discovery
      ports:
        - "8082:8082"
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - "config"
      links:
        - config

    gateway:
      image: gateway:latest
      container_name: gateway
      ports:
        - 8080:8080
      environment:
        - SPRING_PROFILES_ACTIVE=docker
      depends_on:
        - config



